[versions]
agp = "8.11.1"
commonmark = "0.25.1"
kotlin = "2.2.0"
protobuf-plugin = "0.9.5"
dagger-hilt = "2.57"
devtools-ksp = "2.2.0-2.0.2"
google-services = "4.4.3"
jetbrains-dokka = "2.0.0"
firebase-crashlytics = "3.0.6"
accompanistPermissions = "0.37.3"
androidGpxParser = "2.3.1"
composePreferenceLibrary = "1.1.1"
converterMoshi = "3.0.0"
converterProtobuf = "3.0.0"
htmlMermaidDokkaPlugin = "0.6.0"
jtsCore = "1.20.0"
leakcanaryAndroid = "2.14"
mapLibre = "11.13.0"
mapLibreAnnotation = "3.0.2"
androidxJunit = "1.3.0"
converterScalars = "3.0.0"
coreSplashscreen = "1.0.1"
coreTesting = "2.2.0"
datastorePreferences = "1.1.7"
espressoCoreVersion = "3.7.0"
firebaseBom = "34.1.0"
hiltAndroid = "2.57"
hiltCompiler = "2.57"
hiltNavigationCompose = "1.2.0"
junitJupiter = "5.13.4"
coreKtx = "1.16.0"
junit = "4.13.2"
kotlinTestJunit = "1.9.10"
kotlinxCoroutinesCore = "1.10.2"
kotlinxCoroutinesTest = "1.10.2"
kotlinxSerializationJson = "1.9.0"
lifecycleRuntimeKtx = "2.9.2"
activityCompose = "1.10.1"
lifecycleService = "2.9.2"
appcompat = "1.7.1"
coreKtxVersion = "1.7.0"
lifecycleViewmodelCompose = "2.9.2"
loggingInterceptor = "5.1.0"
moshi = "1.15.2"
moshiKotlinCodegen = "1.15.2"
okhttp = "5.1.0"
playServicesLocation = "21.3.0"
preferenceKtx = "1.2.1"
protobufKotlinLite = "4.31.1"
pmtilesreader = "0.3.6"
reorderable = "2.5.1"
retrofit = "3.0.0"
review = "2.0.2"
reviewKtx = "2.0.2"
media3 = "1.8.0"
robolectric = "4.14.1"
roomCompiler = "2.7.2"
roomRuntime = "2.7.2"
rtree2 = "0.9.3"
screenshot = "0.0.1-alpha11"
screenshotValidationApi = "0.0.1-alpha11"
benchmarkCommon = "1.4.0"
lifecycleRuntimeComposeAndroid = "2.9.2"
lifecycleProcess = "2.9.2"
uiautomator = "2.3.0"

# These libraries can't go any higher without breaking map zooming
composeBom = "2025.04.00"
#maplibreComposeMaterial3 = "0.6.0"

[libraries]
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanistPermissions" }
android-gpx-parser = { module = "com.github.ticofab:android-gpx-parser", version.ref = "androidGpxParser" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
androidx-core-testing = { module = "androidx.arch.core:core-testing", version.ref = "coreTesting" }
androidx-datastore = { module = "androidx.datastore:datastore", version.ref = "datastorePreferences" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
androidx-espresso-core-v351 = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCoreVersion" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
androidx-junit-v121 = { module = "androidx.test.ext:junit", version.ref = "androidxJunit" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleViewmodelCompose" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
androidx-preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preferenceKtx" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomCompiler" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomRuntime" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
androidx-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata" }
androidx-uiautomator = { module = "androidx.test.uiautomator:uiautomator", version.ref = "uiautomator" }
commonmark = { module = "org.commonmark:commonmark", version.ref = "commonmark" }
converter-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "converterMoshi" }
converter-protobuf = { module = "com.squareup.retrofit2:converter-protobuf", version.ref = "converterProtobuf" }
converter-scalars = { module = "com.squareup.retrofit2:converter-scalars", version.ref = "converterScalars" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hiltCompiler" }
html-mermaid-dokka-plugin = { module = "com.glureau:html-mermaid-dokka-plugin", version.ref = "htmlMermaidDokkaPlugin" }
jts-core = { module = "org.locationtech.jts:jts-core", version.ref = "jtsCore" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-lifecycle-service = { group = "androidx.lifecycle", name = "lifecycle-service", version.ref = "lifecycleService" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
core-ktx = { group = "androidx.test", name = "core-ktx", version.ref = "coreKtxVersion" }
#androidx-benchmark-common = { group = "androidx.benchmark", name = "benchmark-common", version.ref = "benchmarkCommon" }
androidx-lifecycle-runtime-compose-android = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose-android", version.ref = "lifecycleRuntimeComposeAndroid" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junitJupiter" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlinTestJunit" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesTest" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
composepreferencelibrary = { module = "me.zhanghai.compose.preference:library", version.ref = "composePreferenceLibrary" }
leakcanary-android = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanaryAndroid" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }
#maplibre-compose-material3 = { module = "dev.sargunv.maplibre-compose:maplibre-compose-material3", version.ref = "maplibreComposeMaterial3" }
material3 = { module = "androidx.compose.material3:material3" }
moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
moshi-kotlin-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshiKotlinCodegen" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "playServicesLocation" }
protobuf-kotlin-lite = { module = "com.google.protobuf:protobuf-kotlin-lite", version.ref = "protobufKotlinLite" }
pmtilesreader = { module = "ch.poole.geo.pmtiles-reader:Reader", version.ref = "pmtilesreader" }
reorderable = { module = "sh.calvin.reorderable:reorderable", version.ref = "reorderable" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
review = { module = "com.google.android.play:review", version.ref = "review" }
review-ktx = { module = "com.google.android.play:review-ktx", version.ref = "reviewKtx" }
rtree2 = { module = "com.github.davidmoten:rtree2", version.ref = "rtree2" }
symbol-processing-api = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "devtools-ksp" }
ui = { module = "androidx.compose.ui:ui" }
ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
maplibre = { module = "org.maplibre.gl:android-sdk", version.ref = "mapLibre" }
androidx-media3-common = { group = "androidx.media3", name = "media3-common", version.ref = "media3" }
androidx-media3-common-ktx = { group = "androidx.media3", name = "media3-common-ktx", version.ref = "media3" }
androidx-media3-session = { group = "androidx.media3", name = "media3-session", version.ref = "media3" }
maplibre-annotations = { module = "org.maplibre.gl:android-plugin-annotation-v9", version.ref = "mapLibreAnnotation" }
androidx-lifecycle-process = { group = "androidx.lifecycle", name = "lifecycle-process", version.ref = "lifecycleProcess" }
screenshot-validation-api = { group = "com.android.tools.screenshot", name = "screenshot-validation-api", version.ref = "screenshotValidationApi" }

[plugins]
screenshot = { id = "com.android.compose.screenshot", version.ref = "screenshot"}
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
google-protobuf = { id = "com.google.protobuf", version.ref = "protobuf-plugin" }
dagger-hilt = { id = "com.google.dagger.hilt.android", version.ref = "dagger-hilt" }
devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "devtools-ksp" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebase-crashlytics"}
jetbrains-dokka = { id = "org.jetbrains.dokka", version.ref = "jetbrains-dokka" }
